package main;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;

public class Data {
    String name;
    String surname;
    char gender;
    public Data(){
        randomiseData();
    }
    //names
    public static List<Tuple> names = new ArrayList<>(Arrays.asList(
            new Tuple<String, Character>("Aaron",'m'),
            new Tuple<String, Character>("Noah",'f'),
            new Tuple<String, Character>("Theo",'m'),
            new Tuple<String, Character>("Oliver",'m'),
            new Tuple<String, Character>("George",'m'),
            new Tuple<String, Character>("Leo",'m'),
            new Tuple<String, Character>("Freddie",'m'),
            new Tuple<String, Character>("Arthur",'m'),
            new Tuple<String, Character>("Archie",'m'),
            new Tuple<String, Character>("Charles",'m'),
            new Tuple<String, Character>("Oscar",'m'),
            new Tuple<String, Character>("Henry",'m'),
            new Tuple<String, Character>("Harry",'m'),
            new Tuple<String, Character>("Jack",'m'),
            new Tuple<String, Character>("Luca",'m'),
            new Tuple<String, Character>("Jacob",'m'),
            new Tuple<String, Character>("Thomas",'m'),
            new Tuple<String, Character>("Lucas",'m'),
            new Tuple<String, Character>("Theodore",'m'),
            new Tuple<String, Character>("Max",'m'),
            new Tuple<String, Character>("Isaac",'m'),
            new Tuple<String, Character>("James",'m'),
            new Tuple<String, Character>("Mason",'m'),
            new Tuple<String, Character>("Rory",'m'),
            new Tuple<String, Character>("Logan",'m'),
            new Tuple<String, Character>("William",'m'),
            new Tuple<String, Character>("Elijah",'m'),
            new Tuple<String, Character>("Ethan",'m'),
            new Tuple<String, Character>("Joshua",'m'),
            new Tuple<String, Character>("Hudson",'m'),
            new Tuple<String, Character>("Jude",'m'),
            new Tuple<String, Character>("Louis",'m'),
            new Tuple<String, Character>("Hunter",'m'),
            new Tuple<String, Character>("Alexander",'m'),
            new Tuple<String, Character>("Tobias",'m'),
            new Tuple<String, Character>("Adam",'m'),
            new Tuple<String, Character>("Sebastian",'m'),
            new Tuple<String, Character>("Daniel",'m'),
            new Tuple<String, Character>("Ezra",'m'),
            new Tuple<String, Character>("Rowan",'m'),
            new Tuple<String, Character>("Alec",'m'),
            new Tuple<String, Character>("Dylan",'m'),
            new Tuple<String, Character>("Hugo",'m'),
            new Tuple<String, Character>("Edward",'m'),
            new Tuple<String, Character>("Finn",'m'),
            new Tuple<String, Character>("Grayson",'m'),
            new Tuple<String, Character>("Elliot",'m'),
            new Tuple<String, Character>("Caleb",'m'),
            new Tuple<String, Character>("Benjamin",'m'),
            new Tuple<String, Character>("Bob",'m'),
            new Tuple<String, Character>("Frank",'m'),
            new Tuple<String, Character>("Zachary",'m'),
            new Tuple<String, Character>("Jackson",'m'),
            new Tuple<String, Character>("Oliver",'m'),
            new Tuple<String, Character>("Liam",'m'),
            new Tuple<String, Character>("Stanley",'m'),
            new Tuple<String, Character>("Albert",'m'),
            new Tuple<String, Character>("Joseph",'m'),
            new Tuple<String, Character>("Chester",'m'),
            new Tuple<String, Character>("Carter",'m'),
            new Tuple<String, Character>("David",'m'),
            new Tuple<String, Character>("Samuel",'m'),
            new Tuple<String, Character>("Gabriel",'m'),
            new Tuple<String, Character>("Rupert",'m'),
            new Tuple<String, Character>("Parker",'m'),
            new Tuple<String, Character>("Ralph",'m'),
            new Tuple<String, Character>("Miles",'m'),
            new Tuple<String, Character>("Ryan",'m'),
            new Tuple<String, Character>("Joe",'m'),
            new Tuple<String, Character>("Matthew",'m'),
            new Tuple<String, Character>("Christopher",'m'),
            new Tuple<String, Character>("Jonathan",'m'),
            new Tuple<String, Character>("Robert",'m'),
            new Tuple<String, Character>("Nicholas",'m'),
            new Tuple<String, Character>("Mohammed",'m'),
            new Tuple<String, Character>("Abbey",'f'),
            new Tuple<String, Character>("Ada",'f'),
            new Tuple<String, Character>("Alice",'f'),
            new Tuple<String, Character>("Amber",'f'),
            new Tuple<String, Character>("Amelia",'f'),
            new Tuple<String, Character>("Sophie",'f'),
            new Tuple<String, Character>("Anna",'f'),
            new Tuple<String, Character>("Aurora",'f'),
            new Tuple<String, Character>("Violet",'f'),
            new Tuple<String, Character>("Beatrice",'f'),
            new Tuple<String, Character>("Bella",'f'),
            new Tuple<String, Character>("Camilla",'f'),
            new Tuple<String, Character>("Charlotte",'f'),
            new Tuple<String, Character>("Chloe",'f'),
            new Tuple<String, Character>("Clara",'f'),
            new Tuple<String, Character>("Daisy",'f'),
            new Tuple<String, Character>("Delilah",'f'),
            new Tuple<String, Character>("Edith",'f'),
            new Tuple<String, Character>("Eleanor",'f'),
            new Tuple<String, Character>("Eliza",'f'),
            new Tuple<String, Character>("Elizabeth",'f'),
            new Tuple<String, Character>("Ellie",'f'),
            new Tuple<String, Character>("Elsie",'f'),
            new Tuple<String, Character>("Emily",'f'),
            new Tuple<String, Character>("Emma",'f'),
            new Tuple<String, Character>("Erin",'f'),
            new Tuple<String, Character>("Esme",'f'),
            new Tuple<String, Character>("Eva",'f'),
            new Tuple<String, Character>("Evelyn",'f'),
            new Tuple<String, Character>("Scarlett",'f'),
            new Tuple<String, Character>("Florence",'f'),
            new Tuple<String, Character>("Freya",'f'),
            new Tuple<String, Character>("Grace",'f'),
            new Tuple<String, Character>("Hallie",'f'),
            new Tuple<String, Character>("Hannah",'f'),
            new Tuple<String, Character>("Harper",'f'),
            new Tuple<String, Character>("Harriet",'f'),
            new Tuple<String, Character>("Hazel",'f'),
            new Tuple<String, Character>("Heidi",'f'),
            new Tuple<String, Character>("Holly",'f'),
            new Tuple<String, Character>("Iris",'f'),
            new Tuple<String, Character>("Isabelle",'f'),
            new Tuple<String, Character>("Ivy",'f'),
            new Tuple<String, Character>("Jasmine",'f'),
            new Tuple<String, Character>("Jessica",'f'),
            new Tuple<String, Character>("Lara",'f'),
            new Tuple<String, Character>("Laura",'f'),
            new Tuple<String, Character>("Layla",'f'),
            new Tuple<String, Character>("Lily",'f'),
            new Tuple<String, Character>("Lola",'f'),
            new Tuple<String, Character>("Lucy",'f'),
            new Tuple<String, Character>("Luna",'f'),
            new Tuple<String, Character>("Lauren",'f'),
            new Tuple<String, Character>("Mabel",'f'),
            new Tuple<String, Character>("Maeve",'f'),
            new Tuple<String, Character>("Maisie",'f'),
            new Tuple<String, Character>("Margot",'f'),
            new Tuple<String, Character>("Margaret",'f'),
            new Tuple<String, Character>("Maria",'f'),
            new Tuple<String, Character>("Matilda",'f'),
            new Tuple<String, Character>("Mia",'f'),
            new Tuple<String, Character>("Molly",'f'),
            new Tuple<String, Character>("Olivia",'f'),
            new Tuple<String, Character>("Penelope",'f'),
            new Tuple<String, Character>("Phoebe",'f'),
            new Tuple<String, Character>("Rose",'f'),
            new Tuple<String, Character>("Sara",'f')
            ));
    public static List<String> surnames = new ArrayList<>(Arrays.asList(
            "Adams",
            "Allen",
            "Anderson",
            "Armstrong",
            "Atkinson",
            "Bailey",
            "Baker",
            "Ball",
            "Barker",
            "Barnes",
            "Bell",
            "Bennett",
            "Booth",
            "Bradley",
            "Brooks",
            "Brown",
            "Burton",
            "Butler",
            "Campbell",
            "Carter",
            "Chapman",
            "Clarke",
            "Cole",
            "Collins",
            "Cook",
            "Cooper",
            "Corbyn",
            "Cox",
            "Davidson",
            "Davies",
            "Dawson",
            "Dixon",
            "Edwards",
            "Elliott",
            "Evans",
            "Fisher",
            "Fletcher",
            "Ford",
            "Foster",
            "Fox",
            "Gibson",
            "Graham",
            "Grant",
            "Gray",
            "Green",
            "Griffiths",
            "Hall",
            "Hamilton",
            "Harris",
            "Harrison",
            "Harvey",
            "Henderson",
            "Hill",
            "Holmes",
            "Howard",
            "Hughes",
            "Hunter",
            "Jackson",
            "James",
            "Jenkins",
            "Johnson",
            "Jones",
            "Kelly",
            "Kennedy",
            "King",
            "Knight",
            "Lawrence",
            "Lee",
            "Lewis",
            "Lloyd",
            "Marshall",
            "Martin",
            "Mason",
            "Matthews",
            "McDonald",
            "Miller",
            "Mitchell",
            "Moore",
            "Morgan",
            "Morrison",
            "Murphy",
            "Owen",
            "Palmer",
            "Parker",
            "Payne",
            "Pearce",
            "Pearson",
            "Phillips",
            "Powell",
            "Price",
            "Reynolds",
            "Richardson",
            "Roberts",
            "Robinson",
            "Rogers",
            "Rose",
            "Ross",
            "Russell",
            "Saunders",
            "Scott",
            "Simpson",
            "Smith",
            "Spencer",
            "Stevens",
            "Stewart",
            "Taylor",
            "Thompson",
            "Turner",
            "Walker",
            "Ward",
            "Watson",
            "Webb",
            "West",
            "White",
            "Wilkinson",
            "Williams",
            "Young"
            ));

    public void randomiseData(){
        Random random = new Random();
        int i=random.nextInt(names.size());
        int j=random.nextInt(surnames.size());

        this.name=(String) names.get(i).getFirst();
        this.gender=(char) names.get(i).getSecond();
        this.surname=surnames.get(j);
    }
}